### ISSUE TITLE
Create a password requirement for encryption.

### ISSUE THREAD

**Issue by jopanel** [jopanel/EncryptMyWallet#3]
This is not needed but it is good to help a person protect themselves from a brute force attack on the decryption. 

Rules to follow:

Must be at least 8 characters
Must have upper case and lower case characters
Must have at least 1 number and 1 special character (!@#$%^&*)
Must not have consecutive numbers (1234 etc.)

**Comment by jzet82** [comment]
Please check my pull request #5

**Comment by jopanel** [comment]
Completed by @jzet82 
Thank you
